include!("packet_builders/common.rs");
include!("packet_builders/quest.rs");
include!("packet_builders/combat.rs");
include!("packet_builders/loot.rs");
include!("packet_builders/death.rs");
include!("packet_builders/movement.rs");
include!("packet_builders/progression.rs");
include!("packet_builders/gossip.rs");
include!("packet_builders/item_query.rs");
